### ISSUE TITLE
YouDaoDict can't be installed

### ISSUE THREAD

**Issue by Zephon-H** [Paxxs/Cluttered-bucket#14]
Running installer... error.
ERROR 使用“0”个参数调用“Start”时发生异常:“The requested operation requires elevation”

**Comment by Paxxs** [comment]
YouDaoDict 是带 UAC 前缀的包，**需要管理员权限**。

建议使用 sudo 提权或直接右键以管理员身份运行 powershell/cmd

使用 sudo 示例：

```shell
scoop install sudo
# 在命令前加 sudo
sudo scoop install UAC.YoudaoDict.Pure
```

题外话：

> UAC.YoudaoDict.Pure 是用安装包的形式安装的，scoop 只是通过静默参数安装和卸载，不推荐使用 scoop 处理这类软件
