### ISSUE TITLE
UAC.RDP-Wrapper@1.6.2: Following URLs are not accessible

### ISSUE THREAD

**Issue by cheneric0929** [Paxxs/Cluttered-bucket#16]
URL https://download.fastgit.org/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip is not valid

**Comment by Paxxs** [comment]
It should be caused by fastgit using cloudflare

dc66e07bf563fa95617a204d98cee4e4ea41dfbe
