### ISSUE TITLE
之前那个wsa的呢  https://github.com/Paxxs/BuildWSA/releases/latest

### ISSUE THREAD

**Issue by aogg** [Paxxs/Cluttered-bucket#19]
之前那个wsa的呢  https://github.com/Paxxs/BuildWSA/releases/latest

**Comment by Paxxs** [comment]
嗨你好喔，感谢你的问题——关于该项目消失的问题，是因为违反了GitHub使用协议，所以被禁用了。如果你想继续使用改版的 Windows Subsystem for Android (WSA)，你可以考虑尝试 lsposed 团队提供的本地编译方法，详情在这里：[MagiskOnWSALocal](https://github.com/LSPosed/MagiskOnWSALocal)。

这个项目允许在 WSL（Windows Subsystem for Linux）中编译 WSA，这样你就能继续使用了。不过，要注意这需要一些编译和设置的技术知识，所以确保你了解相关操作。

如果你在使用 MagiskOnWSALocal 过程中遇到问题，可以在该项目的GitHub页面上查找支持或联系 lsposed 团队获取帮助。再次感谢你的支持和理解，希望这个信息对你有所帮助。

祝你好运！
